---

- name: Firewall for RHEL (firewalld)
  hosts: all
  roles:
  - firewall-Linux

  # Defaults to allow

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "addport=80/tcp"

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "addport=80/tcp" --tags add

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "denyport=3389/tcp" --tags deny


  # Multiple ports

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "addport=80/tcp,443/tcp"

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "addport=80/tcp,443/tcp" --tags add

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "denyport=3389/tcp,23/tcp" --tags deny


  # You can also specify a source ip by adding the variable "source=ip or subnet"

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "addport=80/tcp,443/tcp source=192.168.0.10"

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "addport=80/tcp,443/tcp source=172.16.0.0/12" --tags add

  # ansible-playbook Firewall.yml -i hosts -u adminuser -k -e "denyport=3389/tcp,23/tcp source=10.0.0.0/8" --tags deny