---

- name: firewalld deny port {{ item }}
  firewalld:
    zone: public
    port: "{{ item }}"
    source: "{{ source }}"
    permanent: yes
    state: disabled
  notify: reload firewalld
  when: item != 22